@extends('base.base')
@section('content')


<style type="text/css">p{
				font-size: 18px;
			}
			#cmbEscola{
				width: 480px;
			}
			#dadosLotacao{
				padding: 10px;
				border-radius: 12px;
				border-style: groove;
				font-size: 18px;
			}
			.aui select{
				border-radius: 8px;
			}
			.btn{
				border-radius: 5px;
			}
			label{
				font-weight: bold!important;
			}
			.aui label, .aui input, .aui button, .aui select, .aui textarea{
				font-size: 18px!important;
			}
			.aui select{
				font-size: 16px!important;
			}
</style>
<script>

	// Valores (a fonte aqui deve vir de um dataset customizado, porém para este exemplo trabalharei com array bidimensional)
	// Diretorias (idDiretoria, nomeDiretoria) - Dataset

	function dtsListaDiretorias() {
		var diretorias =    [
							["1", "ALTA FLORESTA"],
							["2", "BARRA DO GARÇAS"],
							["3", "CÁCERES"],
							["4", "CONFRESA"],
							["5", "CUIABÁ"],
							["6", "VÁRZEA GRANDE"],
							["7", "DIAMANTINO"],
							["8", "JUÍNA"],
							["9", "MATUPÁ"],
							["10", "PONTES E LACERDA"],
							["11", "PRIMAVERA DO LESTE"],
							["12", "RONDONÓPOLIS"],
							["13", "QUERÊNCIA"],
							["14", "SINOP"],
							["15", "TANGARÁ DA SERRA"]
						];
		return diretorias;
	}

	// Municipios (idMunicipio, nomeMunicipio, idDiretoria) - Dataset
	function dtsListaMunicipios() {
		var municipios = [
					["1", "ALTA FLORESTA", "1"],
					["2","APIACÁS", "1"],
					["3","CARLINDA", "1"],
					["4","NOVA BANDEIRANTES", "1"],
					["5","NOVA CANAÃ DO NORTE", "1"],
					["6","NOVA MONTE VERDE", "1"],
					["7", "PARANAÍTA", "1"],

					["8","ARAGUAIANA", "2"],
					["9","BARRA DO GARÇAS","2"],
					["10","CAMPINÁPOLIS","2"],
					["11","GENERAL CARNEIRO","2"],
					["12","NOVA XAVANTINA","2"],
					["13","NOVO SÃO JOAQUIM","2"],
					["14","PONTAL DO ARAGUAIA","2"],
					["15","PONTE BRANCA","2"],
					["16","RIBEIRÃOZINHO","2"],
					["17","TORIXORÉU","2"],

					["18","CÁCERES","3"],
					["19","ARAPUTANGA","3"],
					["20","CURVELÂNDIA","3"],
					["21","GLÓRIA D'OESTE","3"],
					["22","INDIAVAÍ","3"],
					["23","LAMBARI D'OESTE","3"],
					["24","MIRASSOL D'OESTE","3"],
					["25","PORTO ESPERIDIÃO","3"],
					["26","RESERVA DO CABAÇAL","3"],
					["27","RIO BRANCO","3"],
					["28","SALTO DO CÉU","3"],
					["29","SÃO JOSÉ DOS QUATRO MARCOS","3"],

					["30","CANABRAVA DO NORTE","4"],
					["31","CONFRESA","4"],
					["32","ALTO BOA VISTA","4"],
					["33","LUCIARA","4"],
					["34","PORTO ALEGRE DO NORTE","4"],
					["35","SANTA CRUZ DO XINGU","4"],
					["36","SANTA TEREZINHA","4"],
					["37","SÃO FÉLIX DO ARAGUAIA","4"],
					["38","SÃO JOSÉ DO XINGU","4"],
					["39","VILA RICA","4"],
									
					["40","CHAPADA DOS GUIMARÃES","5"],
					["41","CUIABÁ","5"],
					["42","SANTO ANTÔNIO DO LEVERGER","5"],
					["43","BARÃO DE MELGAÇO","5"],
					["44","NOVA BRASILÂNDIA","5"],
					["45","PLANALTO DA SERRA","5"],
									
					["46","NOSSA SENHORA DO LIVRAMENTO","6"],
					["47","POCONÉ","6"],
					["48","VÁRZEA GRANDE","6"],
					["49","JANGADA","6"],
					["50","ACORIZAL","6"],

					["51","ALTO PARAGUAI","7"],
					["52","ARENÁPOLIS","7"],
					["53","DIAMANTINO","7"],
					["54","NOBRES","7"],
					["55","NORTELÂNDIA","7"],
					["56","NOVA MARINGÁ","7"],
					["57","NOVA MARILÂNDIA","7"],
					["58","NOVA MUTUM","7"],
					["59","ROSÁRIO OESTE","7"],
					["60","SANTA RITA DO TRIVELATO","7"],
					["61","SÃO JOSÉ DO RIO CLARO","7"],
					["62","SANTO AFONSO","7"],
									
					["63","ARIPUANÃ","8"],
					["64","BRASNORTE","8"],
					["65","CASTANHEIRA","8"],
					["66","COLNIZA","8"],
					["67","COTRIGUAÇU","8"],
					["68","JUÍNA","8"],
					["69","JURUENA","8"],
					["70","JUARA","8"],
					["71","NOVO HORIZONTE DO NORTE","8"],
					["72","PORTO DOS GAÚCHOS","8"],

					["73","GUARANTÃ DO NORTE","9"],
					["74","MARCELÂNDIA","9"],
					["75","MATUPÁ","9"],
					["76","NOVA GUARITA","9"],
					["77","NOVO MUNDO","9"],
					["78","PEIXOTO DE AZEVEDO","9"],
					["79","TERRA NOVA DO NORTE","9"],

					["80","CAMPOS DE JÚLIO","10"],
					["81","COMODORO","10"],
					["82","CONQUISTA D'OESTE","10"],
					["83","FIGUEIRÓPOLIS D'OESTE","10"],
					["84","JAURU","10"],
					["85","NOVA LACERDA","10"],
					["86","PONTES E LACERDA","10"],
					["87","RONDOLÂNDIA","10"],
					["88","VALE DE SÃO DOMINGOS","10"],
					["89","VILA BELA DA SANTÍSSIMA TRINDADE","10"],

					["90","CAMPO VERDE","11"],
					["91","GAÚCHA DO NORTE","11"],
					["92","PARANATINGA","11"],
					["93","POXORÉU","11"],
					["94","PRIMAVERA DO LESTE","11"],
					["95","SANTO ANTÔNIO DO LESTE","11"],

					["96","ALTO ARAGUAIA","12"],
					["97","ALTO GARÇAS","12"],
					["98","ALTO TAQUARI","12"],
					["99","ARAGUAINHA","12"],
					["100","DOM AQUINO","12"],
					["101","GUIRATINGA","12"],
					["102","ITIQUIRA","12"],
					["103","JACIARA","12"],
					["104","JUSCIMEIRA","12"],
					["105","PEDRA PRETA","12"],
					["106","RONDONÓPOLIS","12"],
					["107","SÃO JOSÉ DO POVO","12"],
					["108","SÃO PEDRO DA CIPA","12"],
					["109","TESOURO","12"],

					["110","CANARANA","13"],
					["111","BOM JESUS DO ARAGUAIA","13"],
					["112","ÁGUA BOA","13"],
					["113","NOVO SANTO ANTÔNIO","13"],
					["114","NOVA NAZARÉ","13"],
					["115","SERRA NOVA DOURADA","13"],
					["116","QUERÊNCIA","13"],
					["117","RIBEIRÃO CASCALHEIRA","13"],
					["118","COCALINHO","13"],

					["119","CLÁUDIA","14"],
					["120","COLÍDER","14"],
					["121","FELIZ NATAL","14"],
					["122","IPIRANGA DO NORTE","14"],
					["123","ITANHANGÁ","14"],
					["124","ITAÚBA","14"],
					["125","LUCAS DO RIO VERDE","14"],
					["126","NOVA SANTA HELENA","14"],
					["127","NOVA UBIRATÃ","14"],
					["128","SANTA CARMEM","14"],
					["129","SINOP","14"],
					["130","SORRISO","14"],
					["131","TAPURAH","14"],
					["132","UNIÃO DO SUL","14"],
					["133","TABAPORÃ","14"],
					["134","VERA","14"],

					["135","BARRA DO BUGRES","15"],
					["136","CAMPO NOVO DO PARECIS","15"],
					["137","DENISE","15"],
					["138","NOVA OLÍMPIA","15"],
					["139","PORTO ESTRELA","15"],
					["140","SAPEZAL","15"],
					["141","TANGARÁ DA SERRA","15"]];
		return municipios;
	}

	// Escolas (idEscola, nomeEscola, idMunicipio) - Dataset
	function dtsListaEscolas() {
		var escola = [
					["ACORIZAL","EE D. CEZINA ANTONIA BOTELHO","50"],
					["ACORIZAL","EE DOM ANTONIO CAMPELO","50"],
					["ACORIZAL","EE PIO MACHADO","50"],
					["ACORIZAL","EE PONCE DE ARRUDA","50"],
					["AGUA BOA","EE 9 DE JULHO","112"],
					["AGUA BOA","EE ANTONIO GROHS","112"],
					["AGUA BOA","ESCOLA ESTADUAL JARAGUÁ","112"],
					["AGUA BOA","ESCOLA ESTADUAL MILITAR TIRADENTES 3º SGT PM JUSTINO PINHEIRO DOS SANTOS","112"],
					["ALTA FLORESTA","DRE ALTA FLORESTA","1"],
					["ALTA FLORESTA","EE 19 DE MAIO","1"],
					["ALTA FLORESTA","EE BOA ESPERANÇA","1"],
					["ALTA FLORESTA","EE CECILIA MEIRELES","1"],
					["ALTA FLORESTA","EE DOM BOSCO","1"],
					["ALTA FLORESTA","EE GUIMARAES ROSA","1"],
					["ALTA FLORESTA","EE JARDIM UNIVERSITARIO","1"],
					["ALTA FLORESTA","EE JAYME VERISSIMO DE CAMPOS JUNIOR","1"],
					["ALTA FLORESTA","EE LUDOVICO DA RIVA NETO","1"],
					["ALTA FLORESTA","EE MANOEL BANDEIRA","1"],
					["ALTA FLORESTA","EE MILITAR DOM PEDRO II VITÓRIA FURLANI DA RIVA","1"],
					["ALTA FLORESTA","EE MUNDO NOVO","1"],
					["ALTA FLORESTA","EE OURO VERDE","1"],
					["ALTA FLORESTA","EE PROF. MARINES FATIMA DE SA TEIXEIRA","1"],
					["ALTA FLORESTA","EE RUI BARBOSA","1"],
					["ALTO ARAGUAIA","EE ARLINDA PESSOA MORBECK","96"],
					["ALTO ARAGUAIA","EE CARLOS HUGUENEY","96"],
					["ALTO ARAGUAIA","EE MARIA AUXILIADORA","96"],
					["ALTO ARAGUAIA","EE ONECIDIO MANOEL RESENDE","96"],
					["ALTO BOA VISTA","EE JOAO REZENDE DE AZEVEDO","32"],
					["ALTO GARCAS","EE DEP. OSCAR SOARES","97"],
					["ALTO GARCAS","EE DR. YTRIO CORREA","97"],
					["ALTO PARAGUAI","EE ÁGUA SANTA","51"],
					["ALTO PARAGUAI","EE ALEXANDRE GOMES SILVA CHAVES","51"],
					["ALTO PARAGUAI","EE DR. ARNALDO ESTEVAO DE FIGUEIREDO","51"],
					["ALTO PARAGUAI","EE HENRIQUE JOSÉ TRINDADE","51"],
					["ALTO PARAGUAI","EE ZELIA COSTA DE ALMEIDA","51"],
					["ALTO TAQUARI","EE CARLOS IRIGARAY FILHO","98"],
					["ALTO TAQUARI","EE DENNIS MANERICH DE OLIVEIRA","98"],
					["APIACAS","EE INDÍGENA EDUC.BÁSICA MAYROWI APIAKA","2"],
					["APIACAS","EE PORTAL DA AMAZÔNIA","2"],
					["APIACAS","EE VINICIUS DE MORAES","2"],
					["APIACAS","ESCOLA ESTADUAL INDÍGENA ITAWYAK","2"],
					["ARAGUAIANA","EE CEL JERONIMO GOMES SILVA","8"],
					["ARAGUAINHA","EE RUI BARBOSA","99"],
					["ARAPUTANGA","EE JOAQUIM AUGUSTO C MARQUES","19"],
					["ARAPUTANGA","EE NOSSA SENHORA DE FATIMA","19"],
					["ARAPUTANGA","EE PRES TANCREDO DE A NEVES","19"],
					["ARAPUTANGA","EE SEN TEOTONIO VILELA","19"],
					["ARAPUTANGA","ESPSG JOAO SATO","19"],
					["ARENAPOLIS","EE 25 DE OUTUBRO","52"],
					["ARENAPOLIS","EE ALFREDO DE ARAUJO GRANJA","52"],
					["ARENAPOLIS","EE GOV.JOÃO PONCE DE ARRUDA","52"],
					["ARENAPOLIS","EE SEN. FILINTO MULLER","52"],
					["ARIPUANA","EE ADECA VELA ARARA","63"],
					["ARIPUANA","EE DOM FRANCO DALLA VALLE","63"],
					["ARIPUANA","EE INDÍGENA PASAPKAREEJ","63"],
					["ARIPUANA","EE PROFESSOR ELIDIO MURCELLI FILHO","63"],
					["ARIPUANA","EE SÃO FRANCISCO DE ASSIS","63"],
					["BARAO DE MELGACO","EE CEL. ANTONIO PAES DE BARROS","43"],
					["BARAO DE MELGACO","EE CIRO SIQUEIRA GONÇALVES","43"],
					["BARAO DE MELGACO","EE INDÍGENA KOGE EIARI","43"],
					["BARAO DE MELGACO","EE MARIA S. PEIXOTO MOURA","43"],
					["BARRA DO BUGRES","EE 7 DE SETEMBRO","135"],
					["BARRA DO BUGRES","EE ALFREDO JOSÉ DA SILVA","135"],
					["BARRA DO BUGRES","EE EVANGEL. ASSEM. DE DEUS","135"],
					["BARRA DO BUGRES","EE INDÍGENA JULA PARE","135"],
					["BARRA DO BUGRES","EE JOAO CATARINO DE SOUZA","135"],
					["BARRA DO BUGRES","EE JOÃO DE CAMPOS BORGES","135"],
					["BARRA DO BUGRES","EE JOSÉ MARIANO BENTO","135"],
					["BARRA DO BUGRES","EE JULIO MULLER","135"],
					["BARRA DO BUGRES","EE PAULO FREIRE","135"],
					["BARRA DO BUGRES","EE PROF. JULIETA XAVIER BORGES","135"],
					["BARRA DO BUGRES","EE SABINO FERREIRA MAIA","135"],
					["BARRA DO GARCAS","DRE BARRA DO GARÇAS","9"],
					["BARRA DO GARCAS","EE ANTONIO CRISTINO CORTES","9"],
					["BARRA DO GARCAS","EE DA POLÍCIA MILITAR TIRADENTES CB PM VANILSON SILVA CARVALHO","9"],
					["BARRA DO GARCAS","EE DEP. NORBERTO SCHWANTES","9"],
					["BARRA DO GARCAS","EE FRANCISCO DOURADO","9"],
					["BARRA DO GARCAS","EE HERONIDES ARAUJO","9"],
					["BARRA DO GARCAS","EE INDÍGENA DOM FELIPPO RINALDI.","9"],
					["BARRA DO GARCAS","EE INDÍGENA HAMBE","9"],
					["BARRA DO GARCAS","EE INDÍGENA JUCELINO TSEREMAA","9"],
					["BARRA DO GARCAS","EE INDÍGENA MÁRIO JURUNA","9"],
					["BARRA DO GARCAS","EE INDÍGENA ULISSES GUIMARAES","9"],
					["BARRA DO GARCAS","EE IR. DIVA PIMENTEL","9"],
					["BARRA DO GARCAS","EE JOSÉ ANGELO DOS SANTOS","9"],
					["BARRA DO GARCAS","EE MAL. EURICO GASPAR DUTRA","9"],
					["BARRA DO GARCAS","EE SEN. FILINTO MULLER","9"],
					["BARRA DO GARCAS","EEB PROFª MARIA DE LOURDES HORA MORAES","9"],
					["BOM JESUS DO ARAGUAIA","EE INDÍGENA DE EDUC. BÁSICA MARAIWATSEDE","111"],
					["BOM JESUS DO ARAGUAIA","EE PROF GERSON CARLOS DA SILVA","111"],
					["BRASNORTE","EE EWALDO MEYER RODERJAN","64"],
					["BRASNORTE","EE INDÍGENA DE EDUCAÇÃO BÁSICA MYHYINYMYKYTA SKIRIPI","64"],
					["BRASNORTE","EE INDÍGENA TAPURÁ IRANTXE","64"],
					["BRASNORTE","EE INDÍGENA XINUI MYKY","64"],
					["BRASNORTE","EE PROFESSORA NORMA LUCIA NUNES","64"],
					["CÁCERES","DRE CÁCERES","18"],
					["CACERES","ESCOLA ESTADUAL MILITAR TIRADENTES PROFESSOR NATALINO FERREIRA MENDES","18"],
					["CACERES","EE CRIANÇA CIDADÃ","18"],
					["CACERES","EE DR. JOSÉ RODRIGUES FONTES","18"],
					["CACERES","EE FREI AMBROSIO","18"],
					["CACERES","EE LEOPOLDO AMBROSIO FILHO","18"],
					["CACERES","EE ONZE DE MARÇO","18"],
					["CACERES","EE PROF.ANA M.DAS GRAÇAS S.NORONHA","18"],
					["CACERES","EE PROF.DEMETRIO COSTA PEREIRA","18"],
					["CACERES","EE PROFESSOR JOAO FLORENTINO SILVA NETO","18"],
					["CACERES","EE SÃO LUIZ","18"],
					["CACERES","EE SENADOR MARIO MOTTA","18"],
					["CACERES","EE UNIAO E FORÇA","18"],
					["CACERES","EEDIEB PROF MILTON MARQUES CURVO","18"],
					["CACERES","ESCOLA ESTADUAL 12 DE OUTUBRO","18"],
					["CAMPINAPOLIS","EE COUTO MAGALHAES","10"],
					["CAMPINAPOLIS","EE INDÍGENA ALDEIONA","10"],
					["CAMPINAPOLIS","EE INDÍGENA DE EDUCAÇÃO BÁSICA BUTSE WAWE","10"],
					["CAMPINAPOLIS","EE INDÍGENA DE EDUCACAO BÁSICA XAVANTE","10"],
					["CAMPINAPOLIS","EE INDÍGENA ESTRELA","10"],
					["CAMPINAPOLIS","EE INDÍGENA LUIZ RUDZANE EDI OREBWE","10"],
					["CAMPINAPOLIS","EE INDÍGENA RAÍ RÃTE","10"],
					["CAMPINAPOLIS","EE INDÍGENA WA OMORA","10"],
					["CAMPINAPOLIS","EEI DAVID AI'RERO","10"],
					["CAMPINAPOLIS","ESCOLA ESTADUAL INDÍGENA CONSTANTINO TSEREROWÊ","10"],
					["CAMPO NOVO DO PARECIS","EE ARGEU AUGUSTO DE MORAES","136"],
					["CAMPO NOVO DO PARECIS","EE JARDIM DOS IPÊS","136"],
					["CAMPO NOVO DO PARECIS","EE MADRE TARCILA","136"],
					["CAMPO NOVO DO PARECIS","EE MARECHAL CANDIDO RONDON","136"],
					["CAMPO NOVO DO PARECIS","EE PADRE ARLINDO IGNÁCIO DE OLIVEIRA","136"],
					["CAMPO NOVO DO PARECIS","EE UNIÃO DA CHAPADA","136"],
					["CAMPO NOVO DO PARECIS","ESCOLA ESTADUAL PARECIS","136"],
					["CAMPO VERDE","EE ALICE BARBOSA PACHECO","90"],
					["CAMPO VERDE","EE BOA ESPERANCA","90"],
					["CAMPO VERDE","EE JUPIARA","90"],
					["CAMPO VERDE","EE LEDY ANITA BRESCANCIN","90"],
					["CAMPO VERDE","EE ULISSES GUIMARÃES","90"],
					["CAMPO VERDE","EE WALDEMON MORAES COELHO","90"],
					["CAMPOS DE JULIO","EE ANGELINA FRANCISCON MAZUTTI","80"],
					["CANABRAVA DO NORTE","EE ELIAS BENTO","30"],
					["CANARANA","EE 31 DE MARÇO","110"],
					["CANARANA","EE INDÍGENA DE EDUCAÇÃO BÁSICA ETENHIRITIPÁ","110"],
					["CANARANA","EE INDÍGENA SAMUEL SAHUTUWÊ","110"],
					["CANARANA","EE NORBERTO SCHWANTES","110"],
					["CANARANA","EE PAULO FREIRE","110"],
					["CARLINDA","EE FREI CANECA","3"],
					["CARLINDA","EE TANCREDO DE ALMEIDA NEVES","3"],
					["CASTANHEIRA","EE MARIA QUITERIA","65"],
					["CASTANHEIRA","EE MARIO DE ANDRADE","65"],
					["CASTANHEIRA","EE PAULO FREIRE","65"],
					["CHAPADA DOS GUIMARAES","EE CEL. RAFAEL DE SIQUEIRA","40"],
					["CHAPADA DOS GUIMARAES","EE PROF. ANA TEREZA ALBERNAZ","40"],
					["CHAPADA DOS GUIMARAES","EE REUNIDAS DE CACHOEIRA RICA","40"],
					["CHAPADA DOS GUIMARAES","EE SÃO JOSÉ","40"],
					["CLAUDIA","EE DOROTH STONG","119"],
					["CLAUDIA","EE FLORESTAN FERNANDES","119"],
					["CLAUDIA","EE MANOEL SOARES CAMPOS","119"],
					["CLAUDIA","EE RUBEM ALVES","119"],
					["COCALINHO","EE GETULIO VARGAS","118"],
					["COLIDER","EE ANDRÉ ANTONIO MAGGI","120"],
					["COLIDER","EE CAFENORTE","120"],
					["COLIDER","EE CEL. ANTONIO PAES DE BARROS","120"],
					["COLIDER","EE DES.MILTON ARMANDO POMPEU DE BARROS","120"],
					["COLIDER","EE NOVA GALILEIA","120"],
					["COLIDER","EE PALMITAL","120"],
					["COLIDER","EE PROFESSORA ALZIRA MARIA DA SILVA","120"],
					["COLNIZA","EE BERNARDINO GOMES DA LUZ","66"],
					["COLNIZA","EE TARSILA DO AMARAL","66"],
					["COLNIZA","EE VINICIUS DE MORAES","66"],
					["COLNIZA","ESCOLA ESTADUAL MARIA MIRANDA ARAUJO","66"],
					["COLNIZA","ESCOLA ESTADUAL PEDRO BORGES","66"],
					["COMODORO","EE CORA CORALINA","81"],
					["COMODORO","EE DEP.DJALMA CARNEIRO DA ROCHA","81"],
					["COMODORO","EE DONA ROSA FRIGGER PIOVEZAN","81"],
					["COMODORO","EE INDÍGENA MAMAINDE","81"],
					["COMODORO","EEI PIRINEUS DE SOUZA","81"],
					["CONFRESA","DRE CONFRESA","31"],
					["CONFRESA","EE 29 DE JULHO","31"],
					["CONFRESA","EE ANTONIO ALVES DIAS","31"],
					["CONFRESA","EE DA POLÍCIA MILITAR TIRADENTES CB JOSÉ MARTINS DE MOURA","31"],
					["CONFRESA","EE INDÍGENA TAPI ITÃWA","31"],
					["CONFRESA","EE SANTO ANTONIO","31"],
					["CONFRESA","EE SOL NASCENTE","31"],
					["CONFRESA","EE TEOTONIO CARLOS DA CUNHA NETO","31"],
					["CONFRESA","EE WALDIR BENTO DA COSTA","31"],
					["CONFRESA","EEDIEB CREUSLHI DE SOUZA RAMOS","31"],
					["CONQUISTA DO OESTE","EE CONQUISTA D'OESTE","82"],
					["COTRIGUACU","EE ANDRE ANTONIO MAGGI","67"],
					["COTRIGUACU","EE BENICIO TRETEL DA SILVA","67"],
					["COTRIGUACU","EE MARIA DA GLÓRIA VARGAS OCHOA","67"],
					["COTRIGUACU","EE SIDNEY CESAR FUHR","67"],
					["CUIABÁ","DRE CUIABÁ","41"],
					["CUIABÁ","C.E.A.A.D.A. PROFª ARLETE P. MIGUELETTI","41"],
					["CUIABÁ","EE AGENOR FERREIRA LEAO","41"],
					["CUIABÁ","EE ALCEBIADES CALHAO","41"],
					["CUIABÁ","EE ALINA DO NASCIMENTO TOCANTINS","41"],
					["CUIABÁ","EE ANDRE AVELINO RIBEIRO","41"],
					["CUIABÁ","EE ANDRE LUIZ DA SILVA REIS","41"],
					["CUIABÁ","EE ANTONIO EPAMINONDAS","41"],
					["CUIABÁ","EE AUREOLINA EUSTACIA RIBEIRO","41"],
					["CUIABÁ","EE BARAO DE MELGAÇO","41"],
					["CUIABÁ","EE CLEINIA ROSALINA SOUZA","41"],
					["CUIABÁ","EE DIONE AUGUSTA SILVA SOUZA","41"],
					["CUIABÁ","EE DIVA HUGUENEY DE SIQUEIRA BASTOS","41"],
					["CUIABÁ","EE DJALMA FERREIRA DE SOUZA","41"],
					["CUIABÁ","EE DOM FRANCISCO DE AQUINO CORREA","41"],
					["CUIABÁ","EE DOM JOSE DO DESPRAIADO","41"],
					["CUIABÁ","EE DR. ESTEVAO ALVES CORREA","41"],
					["CUIABÁ","EE DR. MARIO DE CASTRO","41"],
					["CUIABÁ","EE DR. HÉLIO PALMA DE ARRUDA","41"],
					["CUIABÁ","EE FILOGONIO CORREA","41"],
					["CUIABÁ","EE FRANCISCO A. FERREIRA MENDES","41"],
					["CUIABÁ","EE GOVERNADOR JOSÉ FRAGELLI","41"],
					["CUIABÁ","EE GUSTAVO KULMAN","41"],
					["CUIABÁ","EE HERMELINDA DE FIGUEIREDO","41"],
					["CUIABÁ","EE HIST. RUBENS DE MENDONÇA","41"],
					["CUIABÁ","EE JOAO BRIENNE DE CAMARGO","41"],
					["CUIABÁ","EE JOAQUINA CERQUEIRA CALDAS","41"],
					["CUIABÁ","EE JOSÉ DE MESQUITA","41"],
					["CUIABÁ","EE JUAREZ RODRIGUES DOS ANJOS","41"],
					["CUIABÁ","EE LEONIDAS ANTERO DE MATOS","41"],
					["CUIABÁ","EE LEOVEGILDO DE MELO","41"],
					["CUIABÁ","EE LICEU CUIABANO MARIA DE ARRUDA MULLER","41"],
					["CUIABÁ","EE MALIK DIDIER NAMER ZAHAFI","41"],
					["CUIABÁ","EE MANOEL CAVALCANTI PROENÇA","41"],
					["CUIABÁ","EE MARCELINA DE CAMPOS","41"],
					["CUIABÁ","EE MARIANA LUIZA MOREIRA","41"],
					["CUIABÁ","EE MILITAR DOM PEDRO II PRESIDENTE MÉDICI","41"],
					["CUIABÁ","EE PADRE FIRMO PINTO DUARTE FILHO","41"],
					["CUIABÁ","EE PADRE JOAO PANAROTTO","41"],
					["CUIABÁ","EE PASCOAL MOREIRA CABRAL","41"],
					["CUIABÁ","EE PE. WANIR DELFINO CESAR","41"],
					["CUIABÁ","EE PE. ERNESTO CAMILO BARRETO","41"],
					["CUIABÁ","EE PROF. ANA MARIA DO COUTO","41"],
					["CUIABÁ","EE PROF. BENEDITO DE CARVALHO","41"],
					["CUIABÁ","EE PROF. HELIODORO CAPISTRANO DA SILVA","41"],
					["CUIABÁ","EE PROF. RAFAEL RUEDA","41"],
					["CUIABÁ","EE PROF. ULISSES CUIABANO","41"],
					["CUIABÁ","EE PROF. PACIANA TORRES DE SANTANA","41"],
					["CUIABÁ","EE PROFª ALICE FONTES PINHEIRO","41"],
					["CUIABÁ","EE PROFESSOR WELSON MESQUITA DE OLIVEIRA","41"],
					["CUIABÁ","EE PROFESSORA MARIA HERMINIA ALVES","41"],
					["CUIABÁ","EE PROFº JOAO CRISOSTOMO DE FIGUEIREDO","41"],
					["CUIABÁ","EE RAIMUNDO PINHEIRO DA SILVA","41"],
					["CUIABÁ","EE RAIO DE SOL","41"],
					["CUIABÁ","EE RODOLFO AUGUSTO T. CURVO","41"],
					["CUIABÁ","EE SANTOS DUMONT","41"],
					["CUIABÁ","EE SENADOR AZEREDO","41"],
					["CUIABÁ","EE SOUZA BANDEIRA","41"],
					["CUIABÁ","EE TANCREDO DE ALMEIDA NEVES","41"],
					["CUIABÁ","EE VICTORINO MONTEIRO DA SILVA","41"],
					["CUIABÁ","EE ZELIA DA COSTA ALMEIDA","41"],
					["CUIABÁ","EEDIEB ANTÔNIO CESÁRIO DE FIGUEIREDO NETO","41"],
					["CUIABÁ","EEDIEB PROF ALMIRA DE AMORIM SILVA","41"],
					["CUIABÁ","ESC.EST.DE ENS.ESPECIAL LIVRE APRENDER","41"],
					["CUIABÁ","ESCOLA ESTADUAL PROFESSORA ELIANE DIGIGOV SANTANA","41"],
					["CUIABÁ","ESCOLA MILITAR TIRADENTES","41"],
					["CURVELANDIA","EE BOA ESPERANÇA","20"],
					["DENISE","EE JOAQUIM A. COSTA MARQUES","137"],
					["DENISE","EE SAGRADO CORAÇÃO DE JESUS","137"],
					["DIAMANTINO","DRE DIAMANTINO","53"],
					["DIAMANTINO","EE ANA MARIA TISSIANI DE OLIVEIRA","53"],
					["DIAMANTINO","EE CASTRO ALVES","53"],
					["DIAMANTINO","EE DECIO LUIZ FURIGO","53"],
					["DIAMANTINO","EE IR. LUCINDA FACCHINI","53"],
					["DIAMANTINO","EE JOÃO BATISTA DE ALMEIDA","53"],
					["DIAMANTINO","EE MILITAR TIRADENTES DR.MANOEL JOSE MURTINHO","53"],
					["DIAMANTINO","EE NILCE MARIA MAGALHAES","53"],
					["DIAMANTINO","EE PLACIDO DE CASTRO","53"],
					["DIAMANTINO","EE SERRA AZUL","53"],
					["DOM AQUINO","EE DOM AQUINO","100"],
					["DOM AQUINO","EE SÃO LOURENÇO","100"],
					["DOM AQUINO","EE VINICIUS DE MORAES","100"],
					["FELIZ NATAL","EE ANDRE ANTONIO MAGGI","121"],
					["FELIZ NATAL","EE INDÍGENA CENTRAL ESTADUAL IKPENG","121"],
					["FIGUEIROPOLIS D'OESTE","EE BARAO DE MELGAÇO","83"],
					["FIGUEIROPOLIS D'OESTE","EE DR. JOSE GENTIL DA SILVA","83"],
					["GAUCHA DO NORTE","EE GERVASIO DOS SANTOS COSTA","91"],
					["GAUCHA DO NORTE","EE INDÍGENA CENTRAL AIHA","91"],
					["GAUCHA DO NORTE","EE INDÍGENA CENTRAL ESTADUAL KARIB","91"],
					["GAUCHA DO NORTE","EE INDÍGENA CENTRAL LEONARDO VILLAS BOAS","91"],
					["GAUCHA DO NORTE","EE INDÍGENA DE EDUCAÇÃO BÁSICA PIYULAGA","91"],
					["GAUCHA DO NORTE","EE INDÍGENA MAVUTSININ","91"],
					["GENERAL CARNEIRO","EE ANTONIO NONATO ROCHA","11"],
					["GENERAL CARNEIRO","EE DR. JOÃO PONCE DE ARRUDA","11"],
					["GENERAL CARNEIRO","EE INDÍGENA ADAO TOPTIVO","11"],
					["GENERAL CARNEIRO","EE INDÍGENA RAIWI A XAVANTE","11"],
					["GENERAL CARNEIRO","EE INDÍGENA SAGRADO CORAÇÃO DE JESUS","11"],
					["GENERAL CARNEIRO","EE INDÍGENA SAO JOSE SANGRADOURO","11"],
					["GLORIA D'OESTE ","EE RUI BARBOSA","21"],
					["GLORIA D'OESTE ","ESCOLA ESTADUAL JOSE BEJO","21"],
					["GUARANTA DO NORTE","EE GUARANTÃ","73"],
					["GUARANTA DO NORTE","EE IRANY JAIME FARINA","73"],
					["GUARANTA DO NORTE","EE KREEN AKARORE","73"],
					["GUARANTA DO NORTE","EE PROFESSOR ELCIO PRATES","73"],
					["GUARANTA DO NORTE","ESCOLA ESTADUAL ALBERT EINSTEIN","73"],
					["GUIRATINGA","E.E. D.MARIA DE LOURDES RIBEIRO FRAGELLI","101"],
					["GUIRATINGA","EE ESTEVÃO DE MENDONÇA","101"],
					["GUIRATINGA","EE GARÇA BRANCA","101"],
					["GUIRATINGA","EE PEDRO FERREIRA","101"],
					["GUIRATINGA","EE SANTA TERESINHA","101"],
					["INDIAVAI","EE PAULINO MODESTO","22"],
					["IPIRANGA DO NORTE","EE ANDRE ANTONIO MAGGI","122"],
					["ITANHANGA","EE BROMILDO LAWISCH","123"],
					["ITANHANGA","EE JOAQUIM BARBOSA DOS SANTOS","123"],
					["ITAUBA","EE PAPA JOAO PAULO II","124"],
					["ITIQUIRA","EE BONIFACIO SACHETTI","102"],
					["ITIQUIRA","EE DOM AQUINO CORREA","102"],
					["JACIARA","EE ANTONIO FERREIRA SOBRINHO","103"],
					["JACIARA","EE CELESTINO CORREA DA COSTA","103"],
					["JACIARA","EE FRANCISCO SOARES DE OLIVEIRA","103"],
					["JACIARA","EE MILTON DA COSTA FERREIRA","103"],
					["JACIARA","EE PREF. ARTUR RAMOS","103"],
					["JACIARA","EE SÃO FRANCISCO","103"],
					["JACIARA","ESCOLA ESTADUAL MODELO SANTO ANTÔNIO","103"],
					["JANGADA","EE ARNALDO ESTEVÃO FIGUEIREDO","49"],
					["JANGADA","EE BENEDITA AUGUSTA LEMES","49"],
					["JANGADA","EE DAMIÃO MAMEDES DO NASCIMENTO","49"],
					["JANGADA","EE DE ED.BÁSICA PROF. ARLINDO DE S. BRUNO","49"],
					["JANGADA","EE LUIZA SOARES BOABAID","49"],
					["JANGADA","EE MAXIMIANA DO NASCIMENTO","49"],
					["JAURU","EE DEP. JOÃO EVARISTO CURVO","84"],
					["JAURU","EE JUSCELINO K. DE OLIVEIRA","84"],
					["JUARA","EE DOM AQUINO CORREA","70"],
					["JUARA","EE CECILIA DE CASTRO BARBOSA","70"],
					["JUARA","EE COM.JOSÉ PEDRO DIAS","70"],
					["JUARA","EE DA POLÍCIA MILITAR TIRADENTES CABO ISRAEL WESLEY PRADO DE ALMEIDA","70"],
					["JUARA","EE DAURY RIVA","70"],
					["JUARA","EE IARA MARIA MINOTTO GOMES","70"],
					["JUARA","EE INDÍGENA DE EDUCAÇÃO BÁSICA JUPORIJUP","70"],
					["JUARA","EE INDÍGENA EDUC. BÁSICA LEONARDO CRIXI APIAKA","70"],
					["JUARA","EE INDÍGENA KRIXI BAROMPO","70"],
					["JUARA","EE LUIZA NUNES BEZERRA","70"],
					["JUARA","EE NIVALDO FRACAROLLI","70"],
					["JUARA","EE OSCAR SOARES","70"],
					["JUARA","EEDIEB JOSÉ DIAS","70"],
					["JUARA","EEI PÉ DE MUTUM","70"],
					["JUÍNA","DRE JUÍNA","68"],
					["JUINA","EE 07 DE SETEMBRO","68"],
					["JUINA","EE 21 DE ABRIL","68"],
					["JUINA","EE ANA NERI","68"],
					["JUINA","EE ANTONIA MOURA MUNIZ","68"],
					["JUINA","EE ANTONIO FRANCISCO LISBOA","68"],
					["JUINA","EE DR. ARTUR ANTUNES MACIEL","68"],
					["JUINA","EE DR. GUILHERME FREITAS DE ABREU LIMA","68"],
					["JUINA","EE MARECHAL RONDON","68"],
					["JUINA","EE MILITAR TIRADENTES PE.EZEQUIEL RAMIN","68"],
					["JUINA","EEI ETEREPUIY","68"],
					["JURUENA","EE ALINE MARIA TEIXEIRA","69"],
					["JURUENA","EE DOM AQUINO CORREA","69"],
					["JUSCIMEIRA","EE ANTONIO JOSE DE LIMA","104"],
					["JUSCIMEIRA","EE DOM VUNIBALDO","104"],
					["JUSCIMEIRA","EE JOAO MATHEUS BARBOSA","104"],
					["JUSCIMEIRA","EE SANTA ELVIRA","104"],
					["JUSCIMEIRA","EE SANTO ANTONIO DE PADUA","104"],
					["JUSCIMEIRA","EE SEN. FILINTO MULLER","104"],
					["LAMBARI D'OESTE","EE PADRE JOSE ANCHIETA","23"],
					["LUCAS DO RIO VERDE","EE ANGELO NADIN","125"],
					["LUCAS DO RIO VERDE","EE DOM BOSCO","125"],
					["LUCAS DO RIO VERDE","EE MANOEL DE BARROS","125"],
					["LUCAS DO RIO VERDE","EE MILITAR TIRADENTES SOLDADO PM ADRIANA MORAIS RAMOS","125"],
					["LUCAS DO RIO VERDE","ESCOLA ESTADUAL MÁRCIO SCHABATT SOUZA","125"],
					["LUCIARA","EE HUMBERTO CASTELO BRANCO","33"],
					["LUCIARA","EE INDÍGENA ESTADUAL HADORI","33"],
					["LUCIARA","EE JUSCELINO KUBISTCHEK","33"],
					["MARCELANDIA","EE INDÍGENA CENTRAL EDUC. BÁSICA KAMADU","74"],
					["MARCELANDIA","EE INDÍGENA EDUCACAO BÁSICA PANAKU","74"],
					["MARCELANDIA","EE PAULO FREIRE","74"],
					["MARCELANDIA","EE PEDRO BIANCHINI","74"],
					["MATUPÁ","DRE MATUPÁ","75"],
					["MATUPA","EE ANTONIO OMETTO","75"],
					["MATUPA","EE BAIRRO UNIÃO","75"],
					["MATUPA","EE CECILIA MEIRELES","75"],
					["MATUPA","EE INDÍGENA TERENA DE KOMOMOYEA KOVÔERO","75"],
					["MATUPA","EE JARDIM DAS FLORES","75"],
					["MATUPA","EE LUIZA MIOTTO FERREIRA","75"],
					["MATUPA","EE SENADOR JONAS PINHEIRO","75"],
					["MIRASSOL D'OESTE","EE 12 DE OUTUBRO","24"],
					["MIRASSOL D'OESTE","EE BENEDITO CESARIO DA CRUZ","24"],
					["MIRASSOL D'OESTE","EE BOA VISTA","24"],
					["MIRASSOL D'OESTE","EE JOAO DE CAMPOS WIDAL","24"],
					["MIRASSOL D'OESTE","EE MADRE CRISTINA","24"],
					["MIRASSOL D'OESTE","EE PADRE JOSE ANCHIETA","24"],
					["MIRASSOL D'OESTE","EE PADRE TIAGO","24"],
					["MIRASSOL D'OESTE","EE PEDRO GALHARDO GARCIA","24"],
					["NOBRES","EE DR. FABIO SILVERIO FARIAS","54"],
					["NOBRES","EE INOCENCIA RACHID JAUDY","54"],
					["NOBRES","EE MARECHAL CANDIDO RONDON","54"],
					["NOBRES","EE PROF. MARIO A. NASSARDEN","54"],
					["NOBRES","EE PROF. NILO POVOAS","54"],
					["NORTELANDIA","EE IDALINA DE FARIAS","55"],
					["NORTELANDIA","EE OLEGARIO MOREIRA DE BARROS","55"],
					["NOSSA SENHORA DO LIVRAMENTO","EE FELICIANO GALDINO","46"],
					["NOSSA SENHORA DO LIVRAMENTO","EE FREI EMILIANO MONTEIRO","46"],
					["NOSSA SENHORA DO LIVRAMENTO","EE JOSÉ CASSEMIRO DE PINHO","46"],
					["NOSSA SENHORA DO LIVRAMENTO","EE JOSÉ DE BARROS MACIEL","46"],
					["NOSSA SENHORA DO LIVRAMENTO","EE JOSÉ DE LIMA BARROS","46"],
					["NOSSA SENHORA DO LIVRAMENTO","EE TEREZA CONCEIÇÃO DE ARRUDA","46"],
					["NOSSA SENHORA DO LIVRAMENTO","EE VER. AMARÍLIO GOMES DA SILVA","46"],
					["NOVA BANDEIRANTES","EE. PROF. VALDOMIRO TEODORO CANDIDO","4"],
					["NOVA BANDEIRANTES","ESCOLA ESTADUAL CEREJEIRAS","4"],
					["NOVA BRASILANDIA","EE PAD. JOSE MARIA DO SACRAMENTO","44"],
					["NOVA CANAA DO NORTE","EE IVONE BORKWSKI DE LIMA","5"],
					["NOVA CANAA DO NORTE","EE NOVA CANAA","5"],
					["NOVA CANAA DO NORTE","EESPSG NOVA UNIAO","5"],
					["NOVA GUARITA","EE 13 DE MAIO","76"],
					["NOVA LACERDA","EE HERMES JOSE SILVA","85"],
					["NOVA MARILANDIA","EE PROFESSORA MURALHA MIRANDA PASSOS","57"],
					["NOVA MARINGA","ESCOLA ESTADUAL OSMAIR PINHEIRO DA SILVA","56"],
					["NOVA MONTE VERDE","EE MACHADO DE ASSIS","6"],
					["NOVA MONTE VERDE","EE MONTE VERDE","6"],
					["NOVA MONTE VERDE","EE PROFESSORA NEIDE ENARA SIMA","6"],
					["NOVA MUTUM","EE DA POLÍCIA MILITAR TIRADENTES CORONEL CELSO HENRIQUE SOUZA BARBOSA","58"],
					["NOVA MUTUM","EE JOSÉ APARECIDO RIBEIRO","58"],
					["NOVA MUTUM","EE PADRE JOHANNES BERTHOLD HENNING","58"],
					["NOVA MUTUM","EE RUI BARBOSA","58"],
					["NOVA MUTUM","EE VIRGILIO CORREA FILHO","58"],
					["NOVA NAZARE","EE TANCREDO NEVES","114"],
					["NOVA OLIMPIA","E E REINALDO DUTRA VILARINHO","138"],
					["NOVA OLIMPIA","EE JOAO MONTEIRO SOBRINHO","138"],
					["NOVA OLIMPIA","EE PROFª FRANCISCA DE SOUZA ALENCAR","138"],
					["NOVA OLIMPIA","EE WILSON DE ALMEIDA","138"],
					["NOVA SANTA HELENA","EE GRACIA EDMUNDO ZEFERINO","126"],
					["NOVA UBIRATA","EE PEDRO BARBOSA","127"],
					["NOVA UBIRATA","ESCOLA ESTADUAL 19 DE DEZEMBRO","127"],
					["NOVA XAVANTINA","EE ARLINDO ESTILAC LEAL","12"],
					["NOVA XAVANTINA","EE JUSCELINO K. OLIVEIRA","12"],
					["NOVA XAVANTINA","EE MILITAR TIRADENTES CB DANNER MAIA BARBOSA","12"],
					["NOVA XAVANTINA","EE MIN. JOAO ALBERTO","12"],
					["NOVO HORIZONTE DO NORTE","EE ROSMAY KARA JOSÉ","71"],
					["NOVO MUNDO","EE EDUCAÇÃO BÁSICA ANDRE ANTONIO MAGGI","77"],
					["NOVO SANTO ANTONIO","EE 29 DE SETEMBRO","113"],
					["NOVO SAO JOAQUIM","EE DINIZ ALVES DE TOLEDO","13"],
					["NOVO SAO JOAQUIM","EE JOSÉ DE ALENCAR","13"],
					["PARANAITA","EE DR. MARIO CORREA DA COSTA","7"],
					["PARANAITA","EE JOAO PAULO I","7"],
					["PARANAITA","EE SÃO PEDRO","7"],
					["PARANATINGA","EE 29 DE JUNHO","92"],
					["PARANATINGA","EE APOLONIO BOURET DE MELO","92"],
					["PARANATINGA","EE INDÍGENA EDUC. BÁSICA ATURUA","92"],
					["PARANATINGA","EE INDÍGENA KURA BAKAIRI","92"],
					["PARANATINGA","EE INDÍGENA PAIHITWARA","92"],
					["PARANATINGA","EE OSVALDO CANDIDO PEREIRA","92"],
					["PEDRA PRETA","EE 10 DE DEZEMBRO","105"],
					["PEDRA PRETA","EE 13 DE MAIO","105"],
					["PEDRA PRETA","EE SÃO PEDRO APÓSTOLO","105"],
					["PEIXOTO DE AZEVEDO","EE 19 DE JULHO","78"],
					["PEIXOTO DE AZEVEDO","EE GARCIA GARRIDO FERMINO","78"],
					["PEIXOTO DE AZEVEDO","EE INDÍGENA DE EDUCAÇÃO BÁSICA METUKTIRE","78"],
					["PEIXOTO DE AZEVEDO","EE INDÍGENA ELIO TURI RONDON","78"],
					["PEIXOTO DE AZEVEDO","EE INDÍGENA GORONÃ","78"],
					["PEIXOTO DE AZEVEDO","EE KREEN AKARORE","78"],
					["PEIXOTO DE AZEVEDO","EE LEONISIO LEMOS MELO","78"],
					["PEIXOTO DE AZEVEDO","EE LUCIENE CARDOSO DE OLIVEIRA","78"],
					["PEIXOTO DE AZEVEDO","EE VINICIUS DE MORAES","78"],
					["PLANALTO DA SERRA","EE ALVARINA ALVES DE FREITAS","45"],
					["POCONE","EE ANTONIO GARCIA","47"],
					["POCONE","EE ANTONIO JOÃO RIBEIRO","47"],
					["POCONE","EE BEL. RIBEIRO DE ARRUDA","47"],
					["POCONE","EE DOM FRANCISCO DE AQUINO CORREA","47"],
					["POCONE","EE EUCARIS NUNES CUNHA MORAIS","47"],
					["POCONE","EE FREI CARLOS VALLETE","47"],
					["POCONE","EE MARIA HELENA DE ARAUJO BASTOS","47"],
					["PONTAL DO ARAGUAIA","EE SÃO MIGUEL","14"],
					["PONTE BRANCA","EE SÃO DOMINGOS SAVIO","15"],
					["PONTES E LACERDA","DRE PONTES E LACERDA","86"],
					["PONTES E LACERDA","EE DEP. DORMEVIL FARIA","86"],
					["PONTES E LACERDA","EE MARIO SPINELLI","86"],
					["PONTES E LACERDA","EE MILITAR TIRADENTES 1º TEN PM CARLOS HENRIQUE PASCHIOTTO SCHEIFER","86"],
					["PONTES E LACERDA","EE SÃO JOSÉ","86"],
					["PONTES E LACERDA","EE VALE DO GUAPORE","86"],
					["PORTO ALEGRE DO NORTE","EE 13 DE MAIO","34"],
					["PORTO ALEGRE DO NORTE","EE ALEXANDRE QUIRINO SOUZA","34"],
					["PORTO ALEGRE DO NORTE","EE ANTONIA LEAO DOS SANTOS","34"],
					["PORTO ALEGRE DO NORTE","EE GILVAN DE SOUZA","34"],
					["PORTO ALEGRE DO NORTE","EE JOSÉ GONCALVES DOS SANTOS","34"],
					["PORTO DOS GAUCHOS","EE JOSÉ ALVES BEZERRA","72"],
					["PORTO DOS GAUCHOS","EE JOSÉ CLETO GIEHL","72"],
					["PORTO DOS GAUCHOS","EE RENATO SPINELLI","72"],
					["PORTO ESPERIDIAO","EE 13 DE MAIO","25"],
					["PORTO ESPERIDIAO","EE INDÍGENA CHIQUITANO JOSÉ TURÍBIO","25"],
					["PORTO ESPERIDIAO","EE INDÍGENA CHIQUITANOS","25"],
					["PORTO ESPERIDIAO","EE PEDRO NECA","25"],
					["PORTO ESPERIDIAO","EE SÃO GERALDO","25"],
					["PORTO ESTRELA","EE REGINA TENORIO DE OLIVEIRA","139"],
					["POXOREU","EE ARGEMIRO RODRIGUES PIMENTEL","93"],
					["POXOREU","EE CEL JULIO MULLER","93"],
					["POXOREU","EE FRANKLIN CASSIANO","93"],
					["POXOREU","EE INDÍGENA MARIMBÚ","93"],
					["POXOREU","EE JOAO BORGES VIEIRA","93"],
					["POXOREU","EE JOAO PEDRO TORRES","93"],
					["POXOREU","EE PE CESAR ALBISETTI","93"],
					["POXOREU","EE POXOREO","93"],
					["POXOREU","EE PRESIDENTE DUTRA","93"],
					["POXOREU","EE PROF JURACY MACEDO","93"],
					["PRIMAVERA DO LESTE","DRE PRIMAVERA DO LESTE","94"],
					["PRIMAVERA DO LESTE","EE CAMPO MASSAPÉ","94"],
					["PRIMAVERA DO LESTE","EE CAMPO VILA UNIÃO","94"],
					["PRIMAVERA DO LESTE","EE CREMILDA DE OLIVEIRA VIANA","94"],
					["PRIMAVERA DO LESTE","EE JOAO RIBEIRO VILELA","94"],
					["PRIMAVERA DO LESTE","EE MONTEIRO LOBATO","94"],
					["PRIMAVERA DO LESTE","EE PADRE ONESTO COSTA","94"],
					["PRIMAVERA DO LESTE","EE PAULO FREIRE","94"],
					["PRIMAVERA DO LESTE","EE PROFª ALDA GAWLINSKI SCOPEL","94"],
					["PRIMAVERA DO LESTE","EE SEBASTIAO PATRICIO","94"],
					["PRIMAVERA DO LESTE","EEDIEB GETULIO DORNELLES VARGAS","94"],
					["PRIMAVERA DO LESTE","ESCOLA ESTADUAL PROFESSORA MARIA SEBASTIANA DE SOUZA","94"],
					["QUERÊNCIA","DRE QUERÊNCIA","116"],
					["QUERÊNCIA","EE COUTINHO UNIAO","116"],
					["QUERÊNCIA","EE INDÍGENA CENTRAL EDUC. BÁSICA KISEDJE","116"],
					["QUERÊNCIA","EE QUERÊNCIA","116"],
					["QUERÊNCIA","ESCOLA ESTADUAL 19 DE DEZEMBRO","116"],
					["QUERÊNCIA","ESCOLA ESTADUAL 20 DE MARÇO","116"],
					["RESERVA DO CABACAL","EE PROF DEMETRIO PEREIRA","26"],
					["RIBEIRAO CASCALHEIRA","EE CEL. ONDINO R. LIMA","117"],
					["RIBEIRAOZINHO","EE ALEXANDRE LEITE","16"],
					["RIO BRANCO","EE DEP.FRANCISCO E.RANGEL TORRES","27"],
					["RONDOLANDIA","EE INDÍGENA EDUCAÇÃO BÁSICA ZARUP WEJ","87"],
					["RONDOLANDIA","EE INDÍGENA SERTANISTA APOENA MEIRELLES","87"],
					["RONDOLANDIA","EE INDÍGENA ZAWÃ KAREJ PANGYJEJ","87"],
					["RONDOLANDIA","EE OLAVO BILAC","87"],
					["RONDONÓPOLIS","DRE RONDONÓPOLIS","106"],
					["RONDONOPOLIS","EE 7 DE SETEMBRO","106"],
					["RONDONOPOLIS","EE ADOLFO AUGUSTO DE MORAES","106"],
					["RONDONOPOLIS","EE ANTONIO G. BALBINO","106"],
					["RONDONOPOLIS","EE D. WUNIBALDO TALLEUR","106"],
					["RONDONOPOLIS","EE DANIEL MARTINS MOURA","106"],
					["RONDONOPOLIS","EE DOMINGOS APARECIDO DOS SANTOS","106"],
					["RONDONOPOLIS","EE EMANUEL PINHEIRO","106"],
					["RONDONOPOLIS","EE FRANCISCA BARROS DE CARVALHO","106"],
					["RONDONOPOLIS","EE JOAQUIM NUNES ROCHA","106"],
					["RONDONOPOLIS","EE JOSÉ MORAES","106"],
					["RONDONOPOLIS","EE JOSÉ RODRIGUES DOS SANTOS","106"],
					["RONDONOPOLIS","EE JOSÉ SALMEN HANZE","106"],
					["RONDONOPOLIS","EE LA SALLE","106"],
					["RONDONOPOLIS","EE LUCAS PACHECO DE CAMARGO","106"],
					["RONDONOPOLIS","EE MAJOR OTAVIO PITALUGA","106"],
					["RONDONOPOLIS","EE MARECHAL DUTRA","106"],
					["RONDONOPOLIS","EE MARIA DE LIMA CADIDE","106"],
					["RONDONOPOLIS","EE MILITAR DOM PEDRO II ANDRE ANTONIO MAGGI","106"],
					["RONDONOPOLIS","EE MILITAR TIRADENTES MAJOR PM ERNESTINO VERISSIMO DA SILVA","106"],
					["RONDONOPOLIS","EE PINDORAMA","106"],
					["RONDONOPOLIS","EE PROF. AMELIA DE OLIVEIRA SILVA","106"],
					["RONDONOPOLIS","EE PROF. CARLOS PEREIRA BARBOSA","106"],
					["RONDONOPOLIS","EE PROF. EUNICE SOUZA DOS SANTOS","106"],
					["RONDONOPOLIS","EE PROF. RENILDA SILVA MORAES","106"],
					["RONDONOPOLIS","EE PROF.ELIZABETH DE FREITAS MAGALHÃES","106"],
					["RONDONOPOLIS","EE PROF.MARIA ELZA FERREIRA INACIO","106"],
					["RONDONOPOLIS","EE PROFESSORA EDITH PEREIRA BARBOSA","106"],
					["RONDONOPOLIS","EE PROFESSORA STELA MARIS VALERIANO DA SILVA","106"],
					["RONDONOPOLIS","EE RAMIRO BERNARDO DA SILVA","106"],
					["RONDONOPOLIS","EE SAGRADO CORAÇÃO DE JESUS","106"],
					["RONDONOPOLIS","EE SANTO ANTONIO","106"],
					["RONDONOPOLIS","EE SÃO JOSÉ OPERÁRIO","106"],
					["RONDONOPOLIS","EE SEBASTIANA R. DE SOUZA","106"],
					["RONDONOPOLIS","EE SILVESTRE GOMES JARDIM","106"],
					["RONDONOPOLIS","EEDIEB PROF ALFREDO MARIEN","106"],
					["RONDONOPOLIS","ESCOLA ESTADUAL ODORICO LEOCÁDIO DA ROSA","106"],
					["ROSARIO OESTE","EE BENEDITA DE ALMEIDA","59"],
					["ROSARIO OESTE","EE CEL. ARTUR BORGES","59"],
					["ROSARIO OESTE","EE ESTEVÃO PEREIRA DE ALMEIDA","59"],
					["ROSARIO OESTE","EE JOAO CALIXTO BERNARDES","59"],
					["ROSARIO OESTE","EE MARECHAL RONDON","59"],
					["ROSARIO OESTE","EE PROFESSORA ELIZABET EVANGELISTA PEREIRA","59"],
					["SALTO DO CEU","EE DEP.FRANCISCO VILLANOVA","28"],
					["SALTO DO CEU","EE VILA PROGRESSO","28"],
					["SANTA CARMEM","EE N. SENHORA APARECIDA","128"],
					["SANTA CRUZ DO XINGU","ESCOLA ESTADUAL SANTA CRUZ","35"],
					["SANTA RITA DO TRIVELATO","EE CANDIDO PORTINARI","60"],
					["SANTA TEREZINHA","EE INDÍGENA DE EDUCAÇÃO BÁSICA HAWALORA","36"],
					["SANTA TEREZINHA","EE INDÍGENA ITXALÁ","36"],
					["SANTA TEREZINHA","EE INDÍGENA TAPIRAPE","36"],
					["SANTA TEREZINHA","EE MARTINIANO CARLOS PEREIRA","36"],
					["SANTA TEREZINHA","EE ROBERVAL COSTA REIS","36"],
					["SANTA TEREZINHA","EE SANTA TEREZINHA","36"],
					["SANTO AFONSO","EE ACAD. LAURO AUGUSTO DE BARROS","62"],
					["SANTO AFONSO","EE GERALDO SANTANA DOS SANTOS","62"],
					["SANTO ANTONIO DO LESTE","EE VANDERLEI CECATTO","95"],
					["SANTO ANTONIO DO LEVERGER","EE GUSTAVO DUTRA","42"],
					["SANTO ANTONIO DO LEVERGER","EE CORREGO DO OURO","42"],
					["SANTO ANTONIO DO LEVERGER","EE FAUSTINO DIAS AMORIM","42"],
					["SANTO ANTONIO DO LEVERGER","EE HERMES RODRIGUES DE ALCÂNTARA","42"],
					["SANTO ANTONIO DO LEVERGER","EE INDÍGENA KOROGEDO PARU","42"],
					["SANTO ANTONIO DO LEVERGER","EE INDÍGENA PIEBAGA","42"],
					["SANTO ANTONIO DO LEVERGER","EE LEONIDAS DE MATOS","42"],
					["SANTO ANTONIO DO LEVERGER","EE MARIA DE ARRUDA MULLER","42"],
					["SANTO ANTONIO DO LEVERGER","EE NAGIB SAAD","42"],
					["SANTO ANTONIO DO LEVERGER","EE OSWALDITA ELIZA TEIXEIRA COUTO","42"],
					["SANTO ANTONIO DO LEVERGER","EE PONTAL DO GLÓRIA","42"],
					["SANTO ANTONIO DO LEVERGER","EE SANTA CLAUDINA","42"],
					["SANTO ANTONIO DO LEVERGER","EE SANTANA DO TAQUARAL","42"],
					["SAO FELIX DO ARAGUAIA","EE INDÍGENA CENTRAL ESTADUAL DIAUARUN","37"],
					["SAO FELIX DO ARAGUAIA","EE PRES. TANCREDO DE A. NEVES","37"],
					["SAO FELIX DO ARAGUAIA","EE PROFESSORA HILDA ROCHA SOUZA","37"],
					["SAO FELIX DO ARAGUAIA","EE SEVERIANO NEVES","37"],
					["SAO JOSE DO POVO","EE LUDOVICO VIEIRA CAMARGO","107"],
					["SAO JOSE DO POVO","EE WELLINGTON FLAVIANO COELHO","107"],
					["SAO JOSE DO RIO CLARO","EE DOMINGOS BRIANTE","61"],
					["SAO JOSE DO RIO CLARO","EE DR. ANISIO JOSE MOREIRA","61"],
					["SAO JOSE DO RIO CLARO","EE SANTANA D' AGUA LIMPA","61"],
					["SAO JOSE DO RIO CLARO","EE SÃO JOSÉ DO RIO CLARO","61"],
					["SAO JOSE DO XINGU","EE ANTONIO GOMES PRIMO","38"],
					["SAO JOSE DO XINGU","EE CINCO DE ABRIL","38"],
					["SAO JOSE DO XINGU","EE INDÍGENA BEPKOROROTI","38"],
					["SAO JOSE DO XINGU","EE INDÍGENA BITAHAMA","38"],
					["SAO JOSE DOS QUATRO MARCOS","EE 15 DE JUNHO","29"],
					["SAO JOSE DOS QUATRO MARCOS","EE BENTO ALEXANDRE DOS SANTOS","29"],
					["SAO JOSE DOS QUATRO MARCOS","EE DEP. BERTOLDO FREIRE","29"],
					["SAO JOSE DOS QUATRO MARCOS","EE LOURENÇO PERUCHI","29"],
					["SAO JOSE DOS QUATRO MARCOS","EE MARECHAL RONDON","29"],
					["SAO JOSE DOS QUATRO MARCOS","EE MARIA EDUARDA PEREIRA SOLDERA","29"],
					["SAO JOSE DOS QUATRO MARCOS","EE MIGUEL BARBOSA","29"],
					["SAO JOSE DOS QUATRO MARCOS","EE SANTA ROSA","29"],
					["SAO PEDRO DA CIPA","EE IR. MIGUELINA CORSO","108"],
					["SAPEZAL","EE ANDRE ANTONIO MAGGI","140"],
					["SAPEZAL","EE LUIZ FRUTUOSO DA SILVA","140"],
					["SERRA NOVA DOURADA","EE ANTONIO CARLOS MOURA","115"],
					["SINOP","DRE SINOP","129"],
					["SINOP","EE BOM JARDIM","129"],
					["SINOP","EE CLEUFA HUBNER","129"],
					["SINOP","EE ÉDINA DALABETTA","129"],
					["SINOP","EE ENIO PIPINO","129"],
					["SINOP","EE JORGE AMADO","129"],
					["SINOP","EE MILITAR TIRADENTES 2º SGT PM CLAUDEMIR FRANÇA MACIEL","129"],
					["SINOP","EE NILZA DE OLIVEIRA PIPINO","129"],
					["SINOP","EE NOSSA SENHORA DA GLÓRIA","129"],
					["SINOP","EE NOSSA SENHORA DE LOURDES","129"],
					["SINOP","EE OLIMPIO JOÃO PISSINATI GUERRA","129"],
					["SINOP","EE PAULO FREIRE","129"],
					["SINOP","EE PROFª EDELI MANTOVANI","129"],
					["SINOP","EE PROFª MARIA DE FATIMA GIMENEZ LOPES","129"],
					["SINOP","EE PROFESSORA ZENI VIEIRA","129"],
					["SINOP","EE RENEE MENEZES","129"],
					["SINOP","EE ROSA DOS VENTOS","129"],
					["SINOP","EE SÃO VICENTE DE PAULA","129"],
					["SINOP","EEDIEB BENEDITO SANTANA DA SILVA FREIRE","129"],
					["SINOP","ESCOLA ESTADUAL CARLOS DRUMMOND DE ANDRADE","129"],
					["SINOP","ESCOLA ESTADUAL PROFESSOR DJALMA GUILHERME DA SILVA","129"],
					["SORRISO","EE 13 DE MAIO","130"],
					["SORRISO","EE CRISTIANO ARAUJO PIRES","130"],
					["SORRISO","EE DA POLÍCIA MILITAR TIRADENTES CABO ANTONIO DILCEU DA SILVA AMARAL","130"],
					["SORRISO","EE IGNACIO SCHEVINSKI FILHO","130"],
					["SORRISO","EE JOSÉ DOMINGOS FRAGA","130"],
					["SORRISO","EE MARIO SPINELLI","130"],
					["SORRISO","ESCOLA ESTADUAL ARLETE MARIA CAPPELLARI","130"],
					["TABAPORA","EE ALFREDO TREUHERZ","133"],
					["TABAPORA","EE FRANCISCO SALDANHA NETO","133"],
					["TABAPORA","EE ZULEIDE DOS SANTOS BARROS","133"],
					["TANGARA DA SERRA","DRE TANGARÁ DA SERRA","141"],
					["TANGARA DA SERRA","EE 13 DE MAIO","141"],
					["TANGARA DA SERRA","EE 29 DE NOVEMBRO","141"],
					["TANGARA DA SERRA","EE ANTONIO HORTOLLANI","141"],
					["TANGARA DA SERRA","EE DA POLÍCIA MILITAR TIRADENTES 1 TEN PM SALOMÃO FERNANDES FERREIRA PIOVESAN","141"],
					["TANGARA DA SERRA","EE DR.HELCIO DE SOUZA","141"],
					["TANGARA DA SERRA","EE INDÍGENA DE EDUCACAO BÁSICA MALAMALATI","141"],
					["TANGARA DA SERRA","EE JONAS LOPES DA SILVA","141"],
					["TANGARA DA SERRA","EE MANOEL MARINHEIRO","141"],
					["TANGARA DA SERRA","EE MIN PETRONIO PORTELA NUNES","141"],
					["TANGARA DA SERRA","EE PATRIARCA DA INDEPENDENCIA","141"],
					["TANGARA DA SERRA","EE PEDRO ALBERTO TAYANO","141"],
					["TANGARA DA SERRA","EE PROF. JOAO BATISTA","141"],
					["TANGARA DA SERRA","EE PROFESSORA JADA TORRES","141"],
					["TANGARA DA SERRA","EE RAMON SANCHES MARQUES","141"],
					["TANGARA DA SERRA","EE VER BENTO MUNIZ","141"],
					["TAPURAH","EE CANDIDO PORTINARI","131"],
					["TERRA NOVA DO NORTE","EE 12 ABRIL","79"],
					["TERRA NOVA DO NORTE","EE LUCAS AUXILIO TONIAZO","79"],
					["TERRA NOVA DO NORTE","EE NORBERTO SCHWANTES","79"],
					["TERRA NOVA DO NORTE","EE TERRA NOVA","79"],
					["TESOURO","EE ARNALDO ESTEVÃO DE FIGUEIREDO","109"],
					["TESOURO","EE XV DE OUTUBRO","109"],
					["TORIXOREU","EE ARTHUR DA COSTA E SILVA","17"],
					["TORIXOREU","EE FEBRONIO RODRIGUES","17"],
					["UNIAO DO SUL","ESCOLA ESTADUAL IVALDINO FRÂNCIO","132"],
					["VALE DE SAO DOMINGOS","ESCOLA ESTADUAL RAINHA DA PAZ","88"],
					["VARZEA GRANDE","DRE VÁRZEA GRANDE","48"],
					["VARZEA GRANDE","CHP PROF.CELIA RODRIGUES DUQUE","48"],
					["VARZEA GRANDE","EE DE ENSINO ESPECIAL LUZ DO SABER","48"],
					["VARZEA GRANDE","EE DEP. EMANUEL PINHEIRO","48"],
					["VARZEA GRANDE","EE DEP. SALIM NADAF","48"],
					["VARZEA GRANDE","EE DOM BOSCO","48"],
					["VARZEA GRANDE","EE DOMINGOS SAVIO BRANDÃO LIMA","48"],
					["VARZEA GRANDE","EE DUNGA RODRIGUES","48"],
					["VARZEA GRANDE","EE GONÇALO BOTELHO DE CAMPOS","48"],
					["VARZEA GRANDE","EE GOVERNADOR DANTE MARTINS DE OLIVEIRA","48"],
					["VARZEA GRANDE","EE GOVERNADOR JOSE GARCIA NETO","48"],
					["VARZEA GRANDE","EE IRENE GOMES DE CAMPOS","48"],
					["VARZEA GRANDE","EE JAIME VERISSIMO DE CAMPOS JUNIOR JAIMINHO","48"],
					["VARZEA GRANDE","EE JOSÉ LEITE DE MORAES","48"],
					["VARZEA GRANDE","EE JULIO STRUBING MULLER","48"],
					["VARZEA GRANDE","EE LUIS PEDROSO DA SILVA","48"],
					["VARZEA GRANDE","EE MANOEL GOMES","48"],
					["VARZEA GRANDE","EE MARIA LEITE MARCOSKI","48"],
					["VARZEA GRANDE","EE MIGUEL BARACAT","48"],
					["VARZEA GRANDE","EE MILITAR TIRADENTES TEN CEL PM LOUIRSON RODRIGUES BENEVIDES","48"],
					["VARZEA GRANDE","EE MISSIONARIO GUNNAR VINGREN","48"],
					["VARZEA GRANDE","EE PEDRO GARDES","48"],
					["VARZEA GRANDE","EE PORFIRIA PAULA DE CAMPOS","48"],
					["VARZEA GRANDE","EE PROF JERCY JACOB","48"],
					["VARZEA GRANDE","EE PROF MARLENE MARQUES DE BARROS","48"],
					["VARZEA GRANDE","EE PROF. ARLETE MARIA DA SILVA","48"],
					["VARZEA GRANDE","EE PROF. FERNANDO LEITE DE CAMPOS","48"],
					["VARZEA GRANDE","EE PROF. HONORIO RODRIGUES AMORIM","48"],
					["VARZEA GRANDE","EE PROF. JOSÉ MENDES MARTINS","48"],
					["VARZEA GRANDE","EE PROF. MARIA MACEDO RODRIGUES","48"],
					["VARZEA GRANDE","EE PROF. VANIL STABILITO","48"],
					["VARZEA GRANDE","EE PROF.ADALGISA DE BARROS","48"],
					["VARZEA GRANDE","EE PROFª ELMAZ GATTAS MONTEIRO","48"],
					["VARZEA GRANDE","EE PROFESSORA ELIZABETH MARIA BASTOS MINEIRO","48"],
					["VARZEA GRANDE","EE TEREZINHA DE JESUS SILVA","48"],
					["VARZEA GRANDE","EE UBALDO MONTEIRO DA SILVA","48"],
					["VARZEA GRANDE","EPG IRMAOS DO CAMINHO","48"],
					["VARZEA GRANDE","ESCOLA ANTONIO GERALDO G. GATTIBONI","48"],
					["VARZEA GRANDE","ESCOLA ESTADUAL PROFª MARIA DA CUNHA BRUNO","48"],
					["VARZEA GRANDE","ESCOLA ESTADUAL DEPUTADO MILTON FIGUEIREDO","48"],
					["VERA","EE N. SR. DO PERPETUO SOCORRO","134"],
					["VILA BELA DA SANTISSIMA TRINDADE","EE 11 DE AGOSTO","89"],
					["VILA BELA DA SANTISSIMA TRINDADE","EE VERENA LEITE DE BRITO","89"],
					["VILA RICA","EE MARIA ESTHER PERES","39"],
					["VILA RICA","EE MILITAR TIRADENTES SD PM ANTÔNIO EUSTÁQUIO DE PAULA","39"]
		];
		return escola;
	}

	// Inicializando o formulário
	function iniciaForm() {
		// Diretorias
		var campoSelect = document.getElementById("cmbDiretoria");
		limparCombo(campoSelect);
		montarCombo(campoSelect, dtsListaDiretorias());
		// Municipios (apenas limpa o campo)
		campoSelect = null;
		campoSelect = document.getElementById("cmbMunicipio");
		limparCombo(campoSelect);
		// Escolas (apenas limpa o campo)
		campoSelect = null;
		campoSelect = document.getElementById("cmbEscola");
		limparCombo(campoSelect);
	}

	// Modificando diretoria
	function modificaDiretoria(diretoria) {
		// Municipios
		var campoSelect = document.getElementById("cmbMunicipio");
		limparCombo(campoSelect);
		montarCombo(campoSelect, dtsListaMunicipios(), diretoria);
		// Escolas (apenas limpa o campo)
		campoSelect = null;
		campoSelect = document.getElementById("cmbEscola");
		limparCombo(campoSelect);
	}

	// Modificando municipio
	function modificaMunicipio(municipio) {
		// Escolas
		var campoSelect = document.getElementById("cmbEscola");
		limparCombo(campoSelect);
		montarCombo(campoSelect, dtsListaEscolas(), municipio);
	}

	// Montando o combo (SELECT)
	function montarCombo(campoCombo, listaValores, filtro) {
		// Adicionar novos elementos ao campo
		if (campoCombo != null) {
			var novoElemento = document.createElement("option");
			novoElemento.value = "";
			novoElemento.text = "-- Escolha a opção --";
			campoCombo.options.add(novoElemento);
			for (var i in listaValores) {
				novoElemento = null;
				novoElemento = document.createElement("option");
				if (filtro == null || filtro == "" || listaValores[i][2] == filtro) {
					novoElemento.value = listaValores[i][0];
					novoElemento.text = listaValores[i][1];
					campoCombo.options.add(novoElemento);
				}
			}
		}
	}

	// Limpando o combo (SELECT)
	function limparCombo(campoCombo) {
		// Limpa o campo caso existam valores
		while (campoCombo.length) {
			campoCombo.remove(0);
		}
	}
	
	function myFunction() {
		fetch('https://www3.seduc.mt.gov.br/documents/8125245/18832748/Informacoes-DRE-Lotacoes-site.csv/9e1bd97d-be57-760d-f9a3-b234cfd99e6c')
				
			.then(response => response.text())
			.then(text => {
				var e = document.getElementById("cmbEscola");
				var opcaoSelecionada = e.options[e.selectedIndex].text;
				var m = document.getElementById("cmbMunicipio");
				var municipioSelecionado = m.options[m.selectedIndex].text;
				
				// An example search call
				var output = searchData(text, opcaoSelecionada);
				// Dump out the results of our search
				for(i=0; i<output.length; i++){
					//$("#output").append(output[i] + "<br>");
					var dadosLotacao=output[i].split(";");
					console.log(municipioSelecionado);
					console.log(dadosLotacao[1].toUpperCase());
					console.log(dadosLotacao[0].toUpperCase());
					console.log("Municipio validação"+municipioSelecionado.trim().valueOf() == dadosLotacao[1].toUpperCase().trim().valueOf());
					console.log("DRE validação"+dadosLotacao[0].toUpperCase().trim().valueOf() == "DRE");
					
					if(municipioSelecionado.trim().valueOf() == dadosLotacao[1].toUpperCase().trim().valueOf() && dadosLotacao[0].toUpperCase().trim().valueOf() == "DRE"){
					
						
						$("#output").append("<div id=\"dadosLotacao\"><b>Polo: </b>"+dadosLotacao[2].toUpperCase() +"<br>"+									
						"<b>Lotação: </b>"+dadosLotacao[4].toUpperCase() +"<br>"+
						"<b>Município:</b> "+dadosLotacao[1].toUpperCase() +
						"<br>"+ "<b>Telefone:</b> "+dadosLotacao[5] +
						"<br>"+ "<b>E-mail:</b> "+dadosLotacao[6] +
						"<br>"+ "<b>Endereço:</b> "+dadosLotacao[8].toUpperCase() +
						"<br>"+ "<b>Bairro:</b> "+dadosLotacao[7].toUpperCase() +
						"<br>"+"<b>CEP:</b> "+dadosLotacao[9] +
						"</div>"+"<br>");
						break;
					}else if(municipioSelecionado.trim().valueOf() == dadosLotacao[1].toUpperCase().trim().valueOf() && dadosLotacao[0].toUpperCase().trim().valueOf() != "DRE"){
					
						
						$("#output").append("<div id=\"dadosLotacao\"><b>Polo: </b>"+dadosLotacao[2].toUpperCase() +"<br>"+										
						"<b>Lotação: </b>"+dadosLotacao[4].toUpperCase() +"<br>"+
						"<b>Município:</b> "+dadosLotacao[1].toUpperCase() +
						"<br>"+ "<b>Telefone:</b> "+dadosLotacao[5] +
						"<br>"+ "<b>E-mail:</b> "+dadosLotacao[6] +
						"<br>"+ "<b>Endereço:</b> "+dadosLotacao[8].toUpperCase() +
						"<br>"+ "<b>Bairro:</b> "+dadosLotacao[7].toUpperCase() +
						"<br>"+"<b>CEP:</b> "+dadosLotacao[9] +
						"</div>"+"<br>");							
					}		
					
				}
			
		})
	}
	
	function searchData(data, busca){
		//Limpa div output
		$("#output").empty();
		
		// Create a temp array to store the found data
		var tempArray = [];

		var arrayBusca = data.split("\n");
		// Loop through the data to see if each array has the search term we need
		for(i=0; i<arrayBusca.length; i++){
			//var pos = $.inArray(search, arrayBusca[i]);
			var pos = arrayBusca[i].search(busca);
			
			// Add found data to the array
			if(pos !== -1){
				tempArray.push(arrayBusca[i]);
			}
		}
		
		// Return the array of matched data
		return tempArray;
	}
	
</script>
<p>Selecione a Diretoria, em seguida o Município, e em seguida a Unidade desejada e clique em Buscar, e acesse o endereço e telefone das lotações. Todos os campos são de preenchimento obrigatório.</p>

<form action="/telefones-uteis-unidades" id="myForm">
<table border="0" cellpadding="0" cellspacing="0">
	<tbody>
		<tr>
			<td><label>Diretoria*</label> <select id="cmbDiretoria" name="diretoria" onchange="modificaDiretoria(this.value);"><option selected="selected" value="">-- Escolha a opção --</option> </select></td>
		</tr>
		<tr>
			<td> </td>
		</tr>
		<tr>
			<td><label>Município*</label> <select id="cmbMunicipio" name="municipio" onchange="modificaMunicipio(this.value);"><option selected="selected" value="">-- Escolha a opção --</option> </select></td>
		</tr>
		<tr>
			<td> </td>
		</tr>
		<tr>
			<td><label>Unidade*</label> <select id="cmbEscola" name="escola"><option selected="selected" value="">-- Escolha a opção --</option> </select></td>
		</tr>
		<tr>
			<td><br />
			<input class="btn" onclick="myFunction()" type="button" value="Busca" /></td>
		</tr>
	</tbody>
</table>
</form>

<div> </div>

<div id="output"> </div>
 



@endsection